api_platform:
  title: Co-living API
  version: 0.0.1
  formats:
    jsonld: ["application/ld+json"]
    json: ["application/json"]
  defaults:
    stateless: true
    cache_headers:
      vary: ["Content-Type", "Authorization", "Origin"]
  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header
