# config/services.yaml
parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  App\Serializer\UserContextBuilder:
    decorates: 'ApiPlatform\State\SerializerContextBuilderInterface'
    arguments:
      $decorated: '@App\Serializer\UserContextBuilder.inner'
      $security: "@security.helper"
    autoconfigure: false
    autowire: true
  App\EventListener\TimestampableListener:
    tags:
      - { name: doctrine.event_listener, event: prePersist }
      - { name: doctrine.event_listener, event: preUpdate }
  App\EventListener\UserPasswordListener:
    tags:
      - { name: doctrine.event_listener, event: prePersist }
      - { name: doctrine.event_listener, event: preUpdate }
