# config/services.yaml
parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  App\Serializer\AddressContextBuilder:
    decorates: 'ApiPlatform\State\SerializerContextBuilderInterface'
    arguments:
      $decorated: '@App\Serializer\AddressContextBuilder.inner'
      $security: "@security.helper"
    autoconfigure: false
    autowire: true

  App\Serializer\UserContextBuilder:
    decorates: 'ApiPlatform\State\SerializerContextBuilderInterface'
    arguments:
      $decorated: '@App\Serializer\UserContextBuilder.inner'
      $security: "@security.helper"
    autoconfigure: false
    autowire: true
